---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: install common packages
  become: true
  action: apt pkg={{item}} state=installed
  with_items:
    - '{{ packages }}'
