---

- name: Install dependecies and libs
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ dependencies }}'
  tags:
    - packages
  become: true

- name: 'Install ruby dependencies'
  apt:
    pkg: '{{ item }}'
    state: 'installed'
  with_items:
    - '{{ ruby_dependencies }}'
  become: true

- name: Install required ruby gems
  with_items: '{{ ruby_gems }}'
  gem:
    name: '{{ item }}'
    state: present
    user_install: 'no'
